import sharePath from './share.svg';
import logoPath from './logo.png';
import logoBigPath from './logo-big.png';
import logoBigPrimaryPath from './logo-big-primary.png';
import logoMovePrimaryPath from './logo-move-primary.gif';
import logoMoveWhitePath from './logo-move-white.gif';
import closeIconPath from './closeIcon.svg';
import filterIconPath from './filterIcon.svg';
import plusPath from './plus.svg';
import clockPath from './clock.svg';
import plusCirclePath from './plusCircle.svg';
import backPath from './back.svg';
import trashcanPath from './trashcan.svg';
import backwardBtnPath from './backwardBtn.svg';
import playBtnPath from './playBtn.svg';
import forwardBtnPath from './forwardBtn.svg';
import whiteCloseBtnPath from './whiteCloseBtn.svg';
import userPath from './user.png';
import sirenGreenPath from './siren-green.svg';
import sirenOrangePath from './siren-orange.svg';
import sirenRedPath from './siren-red.svg';
import pauseBtnPath from './pauseBtn.svg';

export const share: string = sharePath;
export const logo: string = logoPath;
export const logoBig: string = logoBigPath;
export const logoBigPrimary: string = logoBigPrimaryPath;
export const logoMovePrimary: string = logoMovePrimaryPath;
export const logoMoveWhite: string = logoMoveWhitePath;
export const closeIcon: string = closeIconPath;
export const filterIcon: string = filterIconPath;
export const plus: string = plusPath;
export const clock: string = clockPath;
export const plusCircle: string = plusCirclePath;
export const back: string = backPath;
export const trashcan: string = trashcanPath;
export const backwardBtn: string = backwardBtnPath;
export const playBtn: string = playBtnPath;
export const forwardBtn: string = forwardBtnPath;
export const whiteCloseBtn: string = whiteCloseBtnPath;
export const userIcon: string = userPath;
export const sirenGreenIcon: string = sirenGreenPath;
export const sirenOrangeIcon: string = sirenOrangePath;
export const sirenRedIcon: string = sirenRedPath;
export const pauseBtn: string = pauseBtnPath;
