import sharePath from './share.svg';
import logoPath from './logo.png';
import closeIconPath from './closeIcon.svg';
import filterIconPath from './filterIcon.svg';
import plusPath from './plus.svg';
import clockPath from './clock.svg';
import plusCirclePath from './plusCircle.svg';
import backPath from './back.svg';
import trashcanPath from './trashcan.svg';
import backwardBtnPath from './backwardBtn.svg';
import playBtnPath from './playBtn.svg';
import forwardBtnPath from './forwardBtn.svg';
import whiteCloseBtnPath from './whiteCloseBtn.svg';
import userPath from './user.png';

export const share: string = sharePath;
export const logo: string = logoPath;
export const closeIcon: string = closeIconPath;
export const filterIcon: string = filterIconPath;
export const plus: string = plusPath;
export const clock: string = clockPath;
export const plusCircle: string = plusCirclePath;
export const back: string = backPath;
export const trashcan: string = trashcanPath;
export const backwardBtn: string = backwardBtnPath;
export const playBtn: string = playBtnPath;
export const forwardBtn: string = forwardBtnPath;
export const whiteCloseBtn: string = whiteCloseBtnPath;
export const userIcon: string = userPath;
